### ISSUE TITLE
Multi-word locations aren't found

### ISSUE THREAD

**Issue by dandv** [ninya-io/ninya.io#32]
For instance, there are no "meteor" ninyas in "San Francisco", but there are quite a few in "Francisco".

**Comment by cburgdorf** [comment]
Oh, I guess that's a regression introduced by the migration to elasticsearch. Need to take a closer look.

**Comment by cburgdorf** [comment]
Ok, I think the fix is to set the mapping for the location field to `not_analyzed` to get that working. I need to test that out on a separate testing index first.

Here is a explanation of the fix:

http://stackoverflow.com/a/21186102/288703

**Comment by cburgdorf** [comment]
Ok, tested it out. the `not_analyzed` setting works but we are running into exactly the same issue as described in that StackOverflow answer. Since we are not using an analyzer then we have to add the location as another property which is already lowercased and then change our app to use that.

I propose to name it `ninya_location_lowercase`.
