### ISSUE TITLE
Standard query format

### ISSUE THREAD

**Issue by dandv** [ninya-io/ninya.io#33]
I found the query format to be... unique. Any chance to use a standard format, like `location=X&tags=Y` ? As a hashtag if need be, though an ordinary query string would be even better.

**Comment by cburgdorf** [comment]
I have to disagree on that one. Using one query parameter `cmd` gives you more room to come up with a sophisticated query DSL. For instance you could use `location: San Francisco tag: angularjs, javascript` to match users from San Francisco with **either** angularjs **or** javascript skills and or use `location: San Francisco tag: angularjs + javascript` to match user from San Francisco with angularjs **and** javascript skills.

It's not too odd to have this kind of API. E.g [elasticsearch](http://www.elasticsearch.org/guide/en/elasticsearch/reference/master/search-uri-request.html) uses it and resrc.it as well. I would like to rename `cmd` to `q` though because that seems to be more common as a parameter name for that purpose.

**Comment by cburgdorf** [comment]
I changed `cmd` to `q` (with backwards compatibility for old queries). Feel free to reopen if you want to add further notes to the discussion.
